### PR TITLE
Update test dependencies

### PR DESCRIPTION
**Pull request by MatkovIvan**

### CODE REVIEW

**Comment by dhei** [comment]
@MatkovIvan Looks like there's build error in bitrise, could you fix it?

**Comment by MatkovIvan** [comment]
> The support libraries are now available through Google's Maven repository. We no longer support downloading the libraries through the SDK Manager, and that functionality will be removed soon..

Support Library version `26.0.2` is available. Should it be updated too?

**Comment by dhei** [comment]
@MatkovIvan Yes, could you update to Support Library `26.0.2`?

**Comment by guperrot** [comment]
@MatkovIvan does local HTML combined code coverage report work? (after a clean, in sdk folder, the combined one).

**Comment by MatkovIvan** [comment]
@dhei Done.
@guperrot Yep, it works.

**Pull request merged**
